"""
Bot generation wizard.

Generates a self-contained bot directory: config, a thin main.py, and a copy of
the engine. The copy is deliberate — a bot you are running with real money
should not silently change behaviour because the skill was updated underneath it.
"""

from __future__ import annotations

import json
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

GREEN, YELLOW, CYAN, BOLD, DIM, ENDC = (
    "\033[92m", "\033[93m", "\033[96m", "\033[1m", "\033[90m", "\033[0m"
)

MAIN_TEMPLATE = '''#!/usr/bin/env python3
"""
{name} — generated by AlgoTrader on {date}

    python main.py --mode paper     simulated fills, real market prices
    python main.py --mode live      real orders, real money
    python main.py --backtest --start 2026-01-01

Strategy   {strategy}
Universe   {universe}
Capital    Rs {capital:,.0f}
Risk       {risk_pct}% per trade, max {max_positions} positions

Before live mode, work through the checklist in NUANCES.md. The engine enforces
the mechanical guard rails; it cannot tell you whether the strategy has an edge.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

BOT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BOT_DIR))

try:
    from dotenv import load_dotenv
    load_dotenv(BOT_DIR / ".env")
except ImportError:
    pass

from engine.runner import TradingRunner, PreflightError


def load_config() -> dict:
    return json.loads((BOT_DIR / "config.json").read_text())


def main() -> int:
    parser = argparse.ArgumentParser(description="{name}")
    parser.add_argument("--mode", choices=["paper", "live"], default="paper")
    parser.add_argument("--backtest", action="store_true")
    parser.add_argument("--start", help="backtest start, YYYY-MM-DD")
    parser.add_argument("--end", help="backtest end, YYYY-MM-DD")
    args = parser.parse_args()

    config = load_config()

    if args.backtest:
        return run_backtest(config, args)

    if args.mode == "live":
        print("\\n  LIVE MODE — real orders will be placed.")
        print(f"  Capital Rs {{config['capital']:,.0f}}, risk {{config['risk_pct']}}% per trade")
        if input("  Type LIVE to confirm: ").strip() != "LIVE":
            print("  Cancelled.")
            return 1

    runner = TradingRunner(config, mode=args.mode, state_dir=str(BOT_DIR / "state"),
                           log_dir=str(BOT_DIR / "logs"))
    try:
        runner.run()
    except PreflightError as exc:
        print(f"\\n  Preflight failed: {{exc}}")
        return 1
    return 0


def run_backtest(config: dict, args) -> int:
    from engine import backtest
    from engine.analytics import format_report
    from engine.broker import KiteBroker
    from engine.data import DataManager
    from engine.universe import load_universe

    if not args.start:
        print("  --start is required for a backtest")
        return 1

    start = datetime.fromisoformat(args.start)
    end = datetime.fromisoformat(args.end) if args.end else datetime.now()

    broker = KiteBroker(cache_dir=str(BOT_DIR / ".cache"))
    data = DataManager(broker, interval=config.get("interval", "minute"),
                       cache_dir=str(BOT_DIR / ".cache" / "ohlcv"))

    symbols = load_universe(BOT_DIR / config["universe_file"], max_age_days=None)
    print(f"  loading {{len(symbols)}} symbols...")

    frames, ticks = {{}}, {{}}
    for symbol in symbols:
        try:
            frame = data.with_indicators(symbol, start, end, config)
        except Exception as exc:
            print(f"    {{symbol}}: skipped ({{exc}})")
            continue
        if frame.height:
            frames[symbol] = frame
            ticks[symbol] = broker.tick_size(symbol)

    result = backtest.run(frames, config, strategy=config["strategy"],
                          starting_capital=config["capital"], tick_sizes=ticks)
    print(format_report(result.metrics))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

ENV_TEMPLATE = """# Zerodha Kite credentials — get them at https://kite.trade/
# NEVER commit this file.
KITE_API_KEY=your_api_key_here
KITE_API_SECRET=your_api_secret_here
"""

README_TEMPLATE = """# {name}

Generated by AlgoTrader on {date}.

## Setup

1. Put your Kite credentials in `.env` (copy `.env.template`)
2. Authenticate — Kite tokens expire daily around 07:30 IST:

       python -m engine.broker login
       python -m engine.broker token <request_token>

3. Warm the data cache:

       python -c "from engine.broker import KiteBroker; from engine.data import DataManager; \\
                  from engine.universe import load_universe; \\
                  b=KiteBroker(); d=DataManager(b); \\
                  d.warm_cache(load_universe('{universe_file}', max_age_days=None), days=90)"

## Run

    python main.py --backtest --start 2026-01-01    # simulate first
    python main.py --mode paper                     # then paper trade
    python main.py --mode live                      # only after both look right

## Configuration

Everything lives in `config.json`. The values that matter most:

| Key | Value | What it does |
|-----|-------|--------------|
| `risk_pct` | {risk_pct} | percent of capital lost if a stop fires |
| `max_positions` | {max_positions} | concurrent positions |
| `max_portfolio_heat_pct` | {heat} | total open risk across all positions |
| `daily_loss_limit_pct` | {daily_loss} | stops trading for the day |
| `max_consecutive_losses` | {streak} | stops trading after a losing streak |
| `squareoff_time` | {squareoff} | intraday positions flattened |

## Logs

    logs/operational.jsonl   what the bot did
    logs/debug.jsonl         why it did it (including rejected signals)
    logs/errors.jsonl        what broke
    logs/trades.jsonl        closed trades — the analytics input
    state/positions.json     open positions, survives restarts

## Before going live

Read `NUANCES.md` in the skill directory. The engine implements the mechanical
guard rails (tick rounding, reconciliation, stop lifecycle, cooldowns, session
timing), but nothing in it can tell you whether this strategy has an edge on
this universe. Paper trade for at least two weeks and compare the result against
the backtest — a wide win-rate gap means something is wrong, not that live is
"just harder".
"""


def ask(prompt: str, options: list[str], default: int = 1) -> int:
    """Numbered menu. Returns a 1-based index."""
    print(f"\n{BOLD}{prompt}{ENDC}")
    for index, option in enumerate(options, 1):
        marker = f" {DIM}(default){ENDC}" if index == default else ""
        print(f"  {index}. {option}{marker}")

    while True:
        raw = input(f"\n{GREEN}Choice [{default}]:{ENDC} ").strip()
        if not raw:
            return default
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return int(raw)
        print(f"  Enter 1-{len(options)}")


def ask_number(prompt: str, default: float) -> float:
    raw = input(f"\n{GREEN}{prompt} [{default}]:{ENDC} ").strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError:
        print(f"  {YELLOW}Not a number, using {default}{ENDC}")
        return default


def run_wizard(skill_dir: Path) -> int:
    print(f"\n{CYAN}{'═' * 68}{ENDC}")
    print(f"{BOLD}  ALGOTRADER — BOT GENERATOR{ENDC}")
    print(f"{CYAN}{'═' * 68}{ENDC}")

    style_choice = ask(
        "Trading style?",
        ["Intraday — square off daily, minute bars",
         "Swing — hold 3-10 days, 15-minute bars",
         "Positional — hold weeks, daily bars"],
        default=1,
    )
    style = ["intraday", "swing", "positional"][style_choice - 1]

    universe_choice = ask(
        "Universe?",
        ["Nifty 50 — largecap, tightest spreads",
         "Nifty 100",
         "Nifty Midcap 150 — more volatile, breakouts follow through",
         "Nifty Smallcap 250 — widest spreads, check liquidity carefully"],
        default=1,
    )
    universe_key = ["nifty50", "nifty100", "midcap150", "smallcap250"][universe_choice - 1]

    strategy_choice = ask(
        "Strategy?",
        ["Fortress — six-factor confirmation (highest win rate)",
         "Momentum — breakout continuation (suits midcaps)",
         "Mean reversion — VWAP pullback (suits largecaps)"],
        default=1,
    )
    strategy = ["fortress", "momentum", "mean_reversion"][strategy_choice - 1]

    capital = ask_number("Starting capital in lakhs", 10.0) * 100_000

    risk_choice = ask(
        "Risk per trade?",
        ["Conservative — 0.5%", "Balanced — 1.0%", "Aggressive — 2.0%"],
        default=2,
    )
    risk_pct = [0.5, 1.0, 2.0][risk_choice - 1]

    config = json.loads((skill_dir / "config" / "default.json").read_text())
    config.update({
        "strategy": strategy,
        "capital": capital,
        "risk_pct": risk_pct,
        "universe_file": f"universe/{universe_key}.json",
        "interval": {"intraday": "minute", "swing": "15minute", "positional": "day"}[style],
        "product": "MIS" if style == "intraday" else "CNC",
    })

    if style == "intraday":
        config.update({"max_hold_minutes": 45, "sl_atr_mult": 1.2, "risk_reward": 1.5,
                       "close_on_shutdown": True})
    elif style == "swing":
        config.update({"max_hold_minutes": 0, "sl_atr_mult": 2.0, "risk_reward": 2.0,
                       "squareoff_time": None, "close_on_shutdown": False,
                       "trail_pct": 3.0, "max_positions": 8})
    else:
        config.update({"max_hold_minutes": 0, "sl_atr_mult": 2.5, "risk_reward": 3.0,
                       "squareoff_time": None, "close_on_shutdown": False,
                       "trail_pct": 8.0, "max_positions": 10, "skip_lunch": False,
                       "use_regime_sizing": True})

    name = input(f"\n{GREEN}Bot name [trading_bot]:{ENDC} ").strip() or "trading_bot"
    folder = Path(f"{name}_{datetime.now():%Y%m%d_%H%M%S}")

    print(f"\n{BOLD}Summary{ENDC}")
    print(f"  Style      {style} ({config['interval']} bars, {config['product']})")
    print(f"  Strategy   {strategy}")
    print(f"  Universe   {universe_key}")
    print(f"  Capital    Rs {capital:,.0f}")
    print(f"  Risk       {risk_pct}% per trade → max loss Rs {capital * risk_pct / 100:,.0f}")
    print(f"  Folder     {folder}")

    if input(f"\n{GREEN}Generate? [Y/n]:{ENDC} ").strip().lower() in ("n", "no"):
        print("  Cancelled.")
        return 1

    folder.mkdir(parents=True, exist_ok=True)
    (folder / "config.json").write_text(json.dumps(config, indent=2))

    # Copy the engine so the bot is self-contained and version-frozen.
    shutil.copytree(skill_dir / "engine", folder / "engine", dirs_exist_ok=True)
    shutil.copytree(skill_dir / "config", folder / "config", dirs_exist_ok=True)

    substitutions = {
        "name": name,
        "date": datetime.now().strftime("%Y-%m-%d"),
        "strategy": strategy,
        "universe": universe_key,
        "universe_file": config["universe_file"],
        "capital": capital,
        "risk_pct": risk_pct,
        "max_positions": config["max_positions"],
        "heat": config["max_portfolio_heat_pct"],
        "daily_loss": config["daily_loss_limit_pct"],
        "streak": config["max_consecutive_losses"],
        "squareoff": config.get("squareoff_time") or "n/a",
    }

    (folder / "main.py").write_text(MAIN_TEMPLATE.format(**substitutions))
    (folder / "main.py").chmod(0o755)
    (folder / "README.md").write_text(README_TEMPLATE.format(**substitutions))
    (folder / ".env.template").write_text(ENV_TEMPLATE)
    (folder / ".gitignore").write_text(
        ".env\n.kite_session.json\n.cache/\nlogs/\nstate/\n__pycache__/\n*.pyc\n"
    )

    print(f"\n  fetching {universe_key} constituents from NSE...")
    try:
        from engine.universe import fetch_index_constituents, save_universe

        data = fetch_index_constituents(universe_key)
        save_universe(data, folder / config["universe_file"])
        print(f"  {GREEN}✓{ENDC} {data['count']} symbols")
    except Exception as exc:  # noqa: BLE001
        print(f"  {YELLOW}!{ENDC} universe fetch failed ({exc})")
        print(f"    run: ./run.sh universe --indices {universe_key} --out {folder}/universe")

    print(f"\n{GREEN}Generated {folder}{ENDC}\n")
    print(f"{BOLD}Next{ENDC}")
    print(f"  1. cd {folder}")
    print("  2. cp .env.template .env   and fill in your Kite API key/secret")
    print("  3. python -m engine.broker login   (then ...token <request_token>)")
    print("  4. python main.py --backtest --start 2026-01-01")
    print("  5. python main.py --mode paper")
    print(f"\n{DIM}  Read NUANCES.md before step 5, and before ever using --mode live.{ENDC}")
    return 0
